BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE interval';
    EXECUTE IMMEDIATE 'DROP TABLE movement';
    EXECUTE IMMEDIATE 'DROP TABLE classification';
    EXECUTE IMMEDIATE 'DROP TABLE count';
    EXECUTE IMMEDIATE 'DROP TABLE site';
    EXECUTE IMMEDIATE 'DROP TABLE project';
    EXECUTE IMMEDIATE 'DROP TABLE peak';
    EXECUTE IMMEDIATE 'DROP TABLE company';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;